---
# tasks file for olcne

# Apply firewall rules for Workers
-
  firewalld:
    port: '{{ item }}'
    permanent: True
    state: enabled
  loop:
    - 8090/tcp
    - 10250/tcp
    - 10255/tcp
    - 8472/udp
# Reload firewall rules
-
  name: Reloading firewalld
  command:
    cmd: firewall-cmd --reload
...
