---
# tasks file for RKE worker

# Apply firewall rules for Workers
-
  name: Set firewall rules
  firewalld:
    port: '{{ item }}'
    permanent: True
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp
    - 2376/tcp
    - 2379/tcp
    - 2380/tcp
    - 6443/tcp
    - 8472/udp
    - 9099/tcp
    - 10250/tcp
    - 10254/tcp
    - 30000-32767/udp
    - 30000-32767/tcp

# Reload firewall rules
-
  name: Reloading firewalld
  command:
    cmd: firewall-cmd --reload

# Install RKE utility 
- 
  name: Installing RKE utility
  get_url:
    url: https://github.com/rancher/rke/releases/download/v1.0.8/rke_linux-amd64
    dest: /usr/local/bin/rke
    mode: 0555

# Install Kubectl utility
-
  name: Creating kubectl repository file
  blockinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    create: yes
-
  name: Installing kubectl command
  dnf:
    name: kubectl
    state: present

# Creating keys to RKE avi_cluster
- 
  name: Creating .ssh directory
  file:
    path: /home/rke/.ssh/
    owner: rke
    group: docker
    state: directory
    mode: 0700
-
  name: Generating ssh key pair
  openssh_keypair:
    path: /home/rke/.ssh/id_rsa
-
  name: Adjusting ssh config
  blockinfile:
    path: /home/rke/.ssh/config
    block: |
      Host *
          StrictHostKeyChecking no
    create: yes
    mode: 0600
- 
  name: Adjusting ownership of files
  file:
    path: '{{ item }}'
    owner: rke
    group: docker
    mode: 0600
  loop:
    - /home/rke/.ssh/config
    - /home/rke/.ssh/id_rsa
    - /home/rke/.ssh/id_rsa.pub
-
  name: Install EPEL repository to deploy sshpass
  yum:
    name: epel-release
    state: present
-
  name: Install sshpass command
  yum:
    name: sshpass
    state: present
-
  name: Copy public key to the nodes
  command:
    cmd: sshpass -p "{{ rke_password }}" ssh-copy-id -i "/home/rke/.ssh/id_rsa" rke@"{{ item }}" -f
  become: yes
  become_user: rke
  loop: "{{ groups['all'] }}"
...
