---
# tasks file for RKE worker

# Apply firewall rules for Workers
-
  name: Set firewall rules
  firewalld:
    port: '{{ item }}'
    permanent: True
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp
    - 2376/tcp
    - 2379/tcp
    - 2380/tcp
    - 6443/tcp
    - 8472/udp
    - 9099/tcp
    - 10250/tcp
    - 10254/tcp
    - 30000-32767/udp
    - 30000-32767/tcp

# Reload firewall rules
-
  name: Reloading firewalld
  command:
    cmd: firewall-cmd --reload

# Install RKE utility 
- 
  name: Installing RKE utility
  command:
    cmd: wget -O rke https://github.com/rancher/rke/releases/download/v1.0.8/rke_linux-amd64
    args:
      chdir: /tmp
- 
  name: Making executable
  file:
    path: /usr/local/bin/rke
    mode: 0555

# Install Kubectl utility
-
  name: Installing kubectl utility
  
...
